envVarGroups:
  - name: SmartIntern_env_var
    envVars:
      - name: OPENAI_API_KEY
        fromEnv: OPENAI_API_KEY  # Reference the environment variable
      - name: RAPID_API_KEY
        fromEnv: RAPID_API_KEY  # Reference the environment variable

services:
  - type: web
    name: frontend
    env: docker
    plan: free
    dockerfilePath: ./frontend/Dockerfile_frontend
    autoDeploy: true
    envVars:
      - key: BACKEND_URL
        value: http://backend:8000  # internal Docker network reference

  - type: web
    name: backend
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile_backend
    autoDeploy: true
    envVars:
      - key: OPENAI_API_KEY
        fromEnv: OPENAI_API_KEY  # Reference the environment variable from Render dashboard
      - key: RAPID_API_KEY
        fromEnv: RAPID_API_KEY  # Reference the environment variable from Render dashboard