services:
  - type: web
    name: frontend
    env: docker
    plan: free
    dockerfilePath: ./frontend/Dockerfile_frontend
    autoDeploy: true
    envVars:
      - key: BACKEND_URL
        value: http://backend:8000
    envVarGroups:
      - SmartIntern_env_var

  - type: web
    name: backend
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile_backend
    autoDeploy: true
    envVarGroups:
      - SmartIntern_env_var